server_list = {
'Agride':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[2]/td[3]/center/a',
'Atcham':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[3]/td[3]/center/a',
'Boune':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[4]/td[3]/center/a',
'Brumen':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[5]/td[3]/center/a',
'Crail':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[6]/td[3]/center/a',
'Echo':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[7]/td[3]/center/a',
'Eratz':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[8]/td[3]/center/a',
'Furye':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[9]/td[3]/center/a',
'Galgarion':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[10]/td[3]/center/a',
'Henual':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[11]/td[3]/center/a',
'Ilyzaelle':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[12]/td[3]/center/a',
'Jahash':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[13]/td[3]/center/a',
'Julith':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[14]/td[3]/center/a',
'Meriana':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[15]/td[3]/center/a',
'Merkator':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[16]/td[3]/center/a',
'Monocompte IX ':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[17]/td[3]/center/a',
'Monocompte VII':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[18]/td[3]/center/a',
'Monocompte X':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[19]/td[3]/center/a',
'Nidas':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[20]/td[3]/center/a',
'Ombre(Shadow)':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[21]/td[3]/center/a',
'Oto Mustam':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[22]/td[3]/center/a',
'Pandore':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[23]/td[3]/center/a',
'Rubilax':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[24]/td[3]/center/a',
'Temporis I':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[25]/td[3]/center/a',
'Temporis II':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[26]/td[3]/center/a',
'Thanatena':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[27]/td[3]/center/a',
'USH':'/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div[2]/table/tbody/tr[28]/td[3]/center/a'
}